# Generated by Django 4.0.5 on 2022-06-05 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('suburb', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=4)),
                ('postcode', models.CharField(max_length=4)),
                ('listed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('suburb', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=4)),
                ('postcode', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_type', models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('BROTHER', 'Brother'), ('SISTER', 'Sister'), ('UNCLE', 'Uncle')], max_length=20)),
                ('title', models.IntegerField(blank=True, choices=[(1, 'Prof.'), (2, 'Dr.'), (3, 'Mr'), (4, 'Mrs'), (5, 'Ms')], max_length=25, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('accountname', models.CharField(max_length=50)),
                ('bsb', models.CharField(max_length=6)),
                ('accountno', models.CharField(max_length=10)),
                ('listed', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrolment.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=15)),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('residental_status', models.CharField(max_length=50)),
                ('mains_school_name', models.CharField(max_length=50, null=True)),
                ('mains_school_class', models.CharField(max_length=5, null=True)),
                ('mains_school_address', models.CharField(max_length=50, null=True)),
                ('mains_schoolsuburb', models.CharField(max_length=50)),
                ('mains_schoolstate', models.CharField(max_length=10)),
                ('mains_school_postcode', models.CharField(max_length=10)),
                ('medical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrolment.medical')),
            ],
        ),
        migrations.CreateModel(
            name='student_enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_date', models.DateField(max_length=10)),
                ('paid', models.CharField(choices=[('FULL', 'Full'), ('NO', 'No'), ('PARTIAL', 'Partial')], max_length=10)),
                ('term_condition_accept', models.BooleanField(default=True)),
                ('declaration', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrolment.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrolment.student')),
            ],
        ),
    ]
