# Generated by Django 4.0.5 on 2022-06-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.IntegerField(blank=True, choices=[(1, 'Prof.'), (2, 'Dr.'), (3, 'Mr'), (4, 'Mrs'), (5, 'Ms')], null=True),
        ),
    ]
