# Generated by Django 4.0.5 on 2022-06-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolment', '0003_person_user_student_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='contactno',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student_enroll',
            name='declaration',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student_enroll',
            name='term_condition_accept',
            field=models.BooleanField(default=False),
        ),
    ]
