# Generated by Django 4.0.5 on 2022-06-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrolment', '0004_branch_contactno_branch_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='residental_status',
            field=models.CharField(choices=[(1, 'Australian Citizenship'), (2, 'Permanent Resident.'), (3, 'Working Visa'), (4, 'Student Visa'), (5, 'Travel Visa')], max_length=50),
        ),
    ]
